version: "3"
services:
    # Database
    db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        networks:
            - wpNetwork
    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"
        env_file: .env
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        networks:
            - wpNetwork
    # WordPress
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8000:80"
        restart: always
        volumes:
            - wp_data:/var/www/html
            #- ./themes/Divi:/var/www/html/wp-content/themes/Divi
            #- ./plugins/sucuri-scanner:/var/www/html/wp-content/plugins/sucuri-scanner
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: $MYSQL_DATABASE
            WORDPRESS_DB_USER: $MYSQL_USER
            WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
        networks:
            - wpNetwork
networks:
    wpNetwork:
volumes:
    db_data:
    wp_data:
